@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.2.0/C4_Component.puml

Container_Boundary(c1, Frontend, "Frontend") {
    Component_Ext(react, "React", "React")
}

System_Boundary(backend, "Backend") {
    Container(api, "NestJs", "NestJs") {
        Component(auth, "Auth", "authentication module")
        Component(database, "Database", "database configuration module")
        Component(exception, "Exception", "exception module")
        Component(game, "Game", "game module")
        Component(image, "Image", "image module")
        Component(information, "Information", "information module")
        Component(user, "User", "user module")
        Component(order, "Order", "order module")
        Component(project, "Project", "project module")
    }
}

Container_Boundary(c2, "Postgres", "Postgres") {
    Component_Ext(postgres, "Postgres", "Postgres")
}

Container_Boundary(c3, "Redis", "Redis") {
    Component_Ext(bullmq, "BullMQ", "BullMQ")
}


Rel(react, api, "call")

Rel(auth, user, "")
Rel(user, order, "")
Rel(project, order, "")
Rel(project, image, "")
Rel(project, game, "")
Rel(game, order, "")
Rel(game, image, "")

Rel(database, auth, "")
Rel(database, user, "")
Rel(database, order, "")
Rel(database, project, "")
Rel(database, game, "")
Rel(database, image, "")

Rel(exception, auth, "")
Rel(exception, user, "")
Rel(exception, order, "")
Rel(exception, project, "")
Rel(exception, game, "")
Rel(exception, image, "")
Rel(exception, information, "")

Rel(database, postgres, "")

Rel(user, bullmq, "")

@enduml