@startuml
'https://plantuml.com/component-diagram

component "Controller" as controller
component "Service" as service
component "Repository" as repository

controller -down-> service
service -down-> repository

@enduml