@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.2.0/C4_Component.puml

Container_Boundary(backend, "module") {
    Component(Controller, "controller", "")
    Component(Service, "service", "")
    Component(Repository, "repository", "")
}


Rel(Controller, Service, "")
Rel(Service, Repository, "")
Rel(Repository, Service, "")

@enduml