version: "3.8"
volumes:
    postgres_data:
        driver: local

services:
    postgres:
        container_name: GameBoard-Postgres
        image: postgres
        env_file: .env
        environment:
            POSTGRES_DB: ${POSTGRESQL_DB}
            POSTGRES_USER: ${POSTGRESQL_USER}
            POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
        ports:
            - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
        volumes:
            - postgres_data:/var/lib/postgresql/data
#            - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

    keycloak:
        container_name: GameBoard-Keycloak
        image: quay.io/keycloak/keycloak:legacy
        env_file: .env
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: ${POSTGRESQL_DB}
            DB_USER: ${POSTGRESQL_USER}
            DB_SCHEMA: public
            DB_PASSWORD: ${POSTGRESQL_PASS}
            KEYCLOAK_USER: ${KEYCLOAK_USER}
            KEYCLOAK_PASSWORD: ${KEYCLOAK_PASS}
        ports:
            - ${KEYCLOAK_LOCAL_PORT}:${KEYCLOAK_DOCKER_PORT}
        depends_on:
            - postgres



#    backend:
#        image: designer/backend
#        build:
#            context: backend
#            dockerfile: DockerFile
#        ports:
#            - "8080:3000"
#
#    frontend:
#        image: designer/frontend
#        build:
#            context: frontend
#            dockerfile: DockerFile
#        env_file: .env
#        ports:
#            - '3000:3000'
#        volumes:
#            - .:/designer/frontend
#            - /designer/frontend/node_modules
        #        depends_on:
        #            backend:
        #                condition: service_started
