export enum OrderStatus {
  PENDING = 'PENDING',
  CLAIMED = 'CLAIMED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  IN_PROGRESS = 'IN_PROGRESS',
  BLOCKED = 'BLOCKED',
  DONE = 'DONE',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DRAFT = 'DRAFT',
  DISCUSSING = 'DISCUSSING',
  IN_NEGOTIATION = 'IN_NEGOTIATION',
  IN_REVIEW = 'IN_REVIEW',

}