@startuml

title User registration sequence diagram
autonumber

participant "Browser" as browser
participant "Email service" as email
participant "Server" as server
participant "BullMq" as bullmq

browser -> server : send registration request
activate server
server -> server : verify data
server -> server : check if email is already used
alt email is not used
    server -> server : create user
    server -> bullmq : send job to queue
    activate bullmq
    bullmq -> server : process job
    deactivate bullmq
    server -> server : start email send job
    alt email is sent successfully
        server --> browser : send email with activation code
    else email is not sent
        server -> server : log error
    end


else email is already used
    server --> browser : send error message
        deactivate server
end

@enduml
