@startuml

left to right direction

actor "Niezalogowany użytkownik" as Guest

rectangle "Aplikacja" {
    usecase "Logowanie" as UC1
    usecase "Rejestracja" as UC3
    usecase "Weryfikacja konta" as UC4
    usecase "Przeglądanie gier" as UC5
    usecase "Wyszukiwanie gier" as UC6
    usecase "Przeglądanie informacji o grze" as UC7
    usecase "Zmiana języka" as UC8

    Guest -- UC1
    Guest -- UC3
    Guest -- UC5
    Guest -- UC8

    UC3 <.. UC4 : <<extends>>
    UC5 <.. UC6 : <<extends>>
    UC5 <.. UC7 : <<extends>>
}

@enduml
