name: npm CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      POSTGRESQL_DB: gamedb
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASS: postgres
      POSTGRESQL_PORT: 5333
      POSTGRESQL_HOST: localhost
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5333/gamedb?schema=public"
      BACKEND_PORT: 3000
      JWT_SECRET: example_secret
      JWT_EXPIRATION_TIME: 1d


    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ POSTGRESQL_DB }}
          POSTGRES_USER: ${{ POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ POSTGRESQL_PASS }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        working-directory: backend/
        run: npm install

      - name: Run Tests
        working-directory: backend/
        run: npm run test:e2e
        